#-------------------------------
# General Site Settings

menu:
- {name: 'projecten', url: ''}
#- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'over', url: 'pages/about.html'}
- {name: 'contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Persoonlijke pagina van Jochem Pinxteren, regisseur, programmameker, journalist.'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Portfolio Jekyll Theme

  Dit is het portfolio van Jochem Pinxteren.
  
  Ik ben journalist, televisiemaker. Ik maak documentaires en reportageserie over uiteenlopende onderwerpen.  Vaak - maar niet altijd - in de Arabische wereld.
  
  Ik ben regisseur en eindredacteur. Af en toe doe ik ook zelf camerawerk. Mijn volledige cv is op aanvraag beschikbaar.


contact: >
  # Contact

  Neem contact op [per email](mailto:jpinxteren@gmail.com) of [twitter](https://twitter.com/pinxteren).

#-------------------------------
# Work Section

projects:
- {name: 'De Lokroep', folder: 'lokroep', file: 'projects/lokroep.html'}
- {name: 'Planeet Nigeria', folder: 'planeetnigeria', file: 'projects/planeetnigeria.html'}
- {name: 'De verloren kinderen van het Kalifaat', folder: 'kalifaat', file: 'projects/kalifaat.html'}
- {name: 'In het spoor van IS', folder: 'spooris', file: 'projects/spooris.html'}
- {name: 'Danny in Arabistan', folder: 'arabistan', file: 'projects/arabistan.html'}
- {name: 'Streetlab', folder: 'streetlab', file: 'projects/streetlab.html'}
- {name: 'Rambam', folder: 'rambam', file: 'projects/rambam.html'}
- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: '#'}
- {icon: 'instagram', link: '#'}
- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
